### ISSUE TITLE
Dependency Bumps Q2 2023

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1181]
Some big releases recently that needs manual attention and was not handled by dependabot. Making an issue here to ensure we handle all of it

- [x] hyper-rustls 0.23 -> 0.24 + rustls 0.20 -> 0.21.  #1182
- [x] pem 1 -> 2 -> 3 - delayed as requires [MSRV bump to 1.67](https://github.com/jcreekmore/pem-rs/commit/b19353d2849b234672a64cd80a80bdaae7836787#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L12-R13) (when ready; backout [this change](https://github.com/kube-rs/kube/pull/1182/commits/7a012b1d63c4b9fe7e0d55324f6fda360a60b547)) -> finally done in https://github.com/kube-rs/kube/pull/1272
- [x] syn 1 ->2 - failed in #1169 and #1165 - now doable with a `darling` upgrade (0.20) #1213 via https://github.com/TedDriggs/darling/pull/226 - done in #1307
- [x] k8s-openapi 0.18 - #1190
- [x] base64 0.20 -> 0.21 - skipped in #1117 and now we have 3 copies in the tree :upside_down_face:  - [pem 2 uses 0.21](https://github.com/jcreekmore/pem-rs/blob/master/Cargo.toml), as does the next [k8s-openapi](https://github.com/Arnavion/k8s-openapi/blob/master/Cargo.toml), [tower-http does not](https://github.com/tower-rs/tower-http/blob/master/tower-http/Cargo.toml#L28) - done in #1308
- [x] serde_yaml 0.8 -> revisit #980 - done in #1188

EDIT: Core ones are done. Rest needs some time.

**Comment by clux** [comment]
Originally was going to do `base64` 0.21 in the 0.82 bump, but the condescension around their last release makes me want to wait to see for a while instead. https://github.com/rust-lang/cargo/pull/11796#issuecomment-1453674779

**Comment by clux** [comment]
syn/darling can be upgraded as a unit if anyone wants to tackle it.

base64 have generally propagated to the ecosystem so nothing blocking the remains here afaikt.

opening this up in the hopes that someone wants to look at it, had enough toil for one week.
