### ISSUE TITLE
Stability Initiative

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#726]
We plan to provide a series of stability guarantees, policies, and a stable governance via [CNCF](https://www.cncf.io/sandbox-projects/), for kube-rs going forward.

This is an umbrella issue tracking progress and major outstanding work before we mark ourselves as stable. It pertains to the `Stability` category on the [roadmap](https://github.com/orgs/kube-rs/projects/1).

### Background
This is part of a set of [stable client requirements](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md#client-support-level) plus extra requirements that we would like to provide on top so that users can feel safe choosing `kube-rs` as a reliable set of libraries to build upon kubernetes.

There's been a lot of introductory work in this area already as part of our ~~in-progress~~ CNCF setup (#584), along with stability work in #508 (which this issue replaces).

A lot of this is document pertains to process/policy writing that needs to be argued for/against, and then their subsequent implementations and enforcement of these proposed processes through continuous integration.

### Tasks

**Community & Governance**
- [x] adopting the [cncf code of conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) - #593
- [x] [architecture.md](https://github.com/kube-rs/kube-rs/blob/master/architecture.md) - #416
- [x] initial roadmap / governance / security policy / maintainers file / issue templates - #670
- [x] cncf sandbox application #584
- [x] move org-wide policies into [.github repo](https://github.com/kube-rs/.github) or website - #kube-rs/website/issues/11
- [x] achieve CII best practices badge #737

**Policies & Clarity**:
- [x] documented release process - via [release.toml](https://github.com/kube-rs/kube-rs/blob/master/release.toml) by [release team](https://github.com/orgs/kube-rs/teams/release)
- [x] minimum rust version (msrv) defined and under CI - #668
- [x] N documented users - #735 
- [x] document support level per-platform - https://github.com/kube-rs/website/pull/18
- [x] document kubernetes flavour test levels per-platform - https://github.com/kube-rs/website/pull/18
- panic policy -> delayed- #634
- [x] library documentation `#[deny(missing_docs)]` at root of repos
  * [x] remove last few `#[allow(missing_docs)]` overrides - #728 
  * ~~doctest readme~~ - #736 
- [x] minimum supported kubernetes version - #684 - kube-rs/k8s-pb#10 and https://github.com/kube-rs/website/pull/19
- [x] deprecation policies - https://github.com/kube-rs/website/pull/18
  * [x] decide on a strategy for [deprecated attrs](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute) - https://github.com/kube-rs/website/pull/18
  * [x] document strategy and for how long we deprecate - currently have done 5 versions (e.g. [`try_flatten_applied`](https://github.com/kube-rs/kube-rs/blob/d0bf02f9c0783a3087b83633f2fa899d8539e91d/kube-runtime/src/utils/mod.rs#L30-L40)) - https://github.com/kube-rs/website/pull/18
- [x] document interface changes pre 1.0 - https://github.com/kube-rs/website/pull/18
- document change policy post 1.0 - delayed - https://github.com/kube-rs/kube-rs/issues/923
- [x] investigate a way to gradually introduce unstable features - https://github.com/kube-rs/website/pull/18

**Security**:
- [x] trust and authority of dependencies
  * [x] `cargo deny` multiple-versions - #711
  * [x] `cargo deny` unknown git sources - #727 
  * [x] `cargo deny` strict licenses and rustsec vulnerabilities - #611
- [x] [security policy](https://github.com/kube-rs/.github/blob/main/SECURITY.md)
- [x] [cargo audit on CI](https://github.com/kube-rs/kube-rs/blob/master/.github/workflows/audit.yml)
- limit dependabot lock-step upgrade issues:
  * [x] `kube` as a super-crate facade - #651
  * ~~re-export generated structs from `kube`~~? - maybe post k8s-pb
- [x] `#[forbid(unsafe_code)]` for `cargo-geiger` :lock: - #734
- [x] fortify secrets with secrecy wrappers - #751

**Continuous Integration**:
- [x] run tests in strategy.matrix for linux/mac
- [x] extend unit test set to windows - #566
- [x] provide coverage builds and test policies for prs - #745
- integration/[e2e](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md) extensions:
  * [x] convert e2e test to run as matrix job against clusters (k3d first) - #924
  * [x] run integration as a matrix job against min supported kubernetes versions - #924
  * ~~extend e2e test matrix job to be able to run on both k3d and extra cluster~~ - we would need one first
  * ~~use cloud clusters to point to in CI?~~ (maybe [sponsored](https://foundation.rust-lang.org/news/2021-11-16-news-announcing-cloud-compute-initiative/) or / [cncf service](https://www.cncf.io/services-for-projects/#continuous-integration) / [cncf community](https://github.com/cncf/cluster))
  * extend e2e test to cover token renewal -> delayed #832

**Comment by clux** [comment]
We've accomplished the main overarching thing we wanted to achieve to at least mark us stable w.r.t. the client stability doc:

[![Client Support Level; Stable](https://img.shields.io/badge/kubernetes%20client-stable-green.svg?style=plastic&colorA=306CE8)](https://kube.rs/stability) 🎉 

So will close this as I'm tired of having this massive issue around (not a huge fan of the ergonomics of umbrella issues after having tried them).

There are three minor points that did not make it and will need some clarity/improvements in the future, but they have their own issues:
- panic policy - https://github.com/kube-rs/kube/issues/634
- e2e test for cover token renewal - https://github.com/kube-rs/kube/issues/832
- document change policy post 1.0 - https://github.com/kube-rs/kube/issues/923
